### ISSUE TITLE
Only works with Basic Grid

### ISSUE THREAD

**Issue by jcballesteros** [ckan/ckanext-basiccharts#38]
After a fresh install in 2.8.2 with this plugins:

ckan.plugins = datastore datapusher stats text_view image_view recline_view linechart barchart piechart basicgrid

Only works basicgrid. Barchart, piechar and linechart give me this error:

After a deep search, the error is: " ckan.views.filters is undefined" in javascript

In CKAN 2.7.4 works perfect (with the same resource).

**Comment by BrechtPorrez** [comment]
Any luck solving this issue? I have the same problem!

**Comment by jcballesteros** [comment]
We forked the repository (https://github.com/localidata/ckanext-basiccharts) and now works in CKAN 2.8.5
